spring:
  datasource:
    url: jdbc:mysql://192.168.1.141:3306/hcms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    username: root
    password: root
    druid:
      max-active: 3000
      initial-size: 20
      max-wait: 600000
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  #redis配置
  redis:
    database: 0
    host: 192.168.1.141
    port: 6379
    password: 123456
    timeout: 3600
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1


# 默认占用端口2002 可配置
jodconverter:
  local:
    enabled: true
    office-home: D:\Program Files\LibreOffice



